## PyTorch Fundamentals

Source: https://www.learnpytorch.io/00_pytorch_fundamentals/

## PyTorch Workflow

1. Get the data ready. Convert them to tensors
2. Build or pick a model including loss function, optimizer and build a training loop
3. Fit the model to the data and make a prediction
4. Evaluate the model/Hyperparameter tuning
5. Improve the model through experimentation

In [4]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)
!nvcc --version

2.5.1+cu121
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


## What is a Tensor?
1. It is a fundamental data structure in PyTorch used for storing and manipulating data.
2. Tensor computations can be parallelized on GPUs to improve the speed.
3. Tensors can be scalars, vectors or multi-dimensional arrays.

In [5]:
scalar = torch.tensor(7)
print(type(scalar))
print(f"Num of dimensions = {scalar.ndim}, since it is a scalar")
print(scalar.item())
print(f"Shape of scalar = {scalar.shape}")

<class 'torch.Tensor'>
Num of dimensions = 0, since it is a scalar
7
Shape of scalar = torch.Size([])


In [6]:
vector = torch.tensor([7,7])
print(f"Num of dimensions = {vector.ndim}")
print(f"Shape = {vector.shape}")

Num of dimensions = 1
Shape = torch.Size([2])


In [8]:
matrix = torch.tensor([[7,8],
                       [9,10]])
print("No of dimensions", matrix.ndim)
print("Shape of matrix",matrix.shape)

No of dimensions 2
Shape of matrix torch.Size([2, 2])


In [10]:
tensor = torch.tensor([[[1,2,],
                        [3,4],
                        [5,6]]])
print("No of dimensions",tensor.ndim)
print("SHape of tensor", tensor.shape)

No of dimensions 3
SHape of tensor torch.Size([1, 3, 2])


## Random tensor initialization
Used to create tensors randomly without explicitly specifying the input data

In [13]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.5442, 0.3386, 0.5666],
        [0.9440, 0.3334, 0.6510]])

In [18]:
random_img_tensor = torch.rand(size=(3,224,224))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [27]:
# create a tensor of all zeros
zeros = torch.zeros(2,3)
print(zeros)
print(zeros*random_tensor)
zeros.dtype

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.float32

In [28]:
# create a tensor of all ones
ones = torch.ones(2,3)
print(ones)
print(ones*random_tensor)
ones.dtype

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.5442, 0.3386, 0.5666],
        [0.9440, 0.3334, 0.6510]])


torch.float32

## Range and tensor-like array creation

The end is not included. [start,end)

In [36]:
one_ten = torch.arange(start=1, end=11, step=1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
ten_zeros = torch.zeros_like(one_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])