<a href="https://colab.research.google.com/github/srikrish2812/pytorch_practice/blob/main/torch_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Source: https://www.learnpytorch.io/00_pytorch_fundamentals/

## PyTorch Workflow

1. Get the data ready. Convert them to tensors
2. Build or pick a model including loss function, optimizer and build a training loop
3. Fit the model to the data and make a prediction
4. Evaluate the model/Hyperparameter tuning
5. Improve the model through experimentation

In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)
!nvcc --version

2.5.1+cu121
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


## What is a Tensor?
1. It is a fundamental data structure in PyTorch used for storing and manipulating data.
2. Tensor computations can be parallelized on GPUs to improve the speed.
3. Tensors can be scalars, vectors or multi-dimensional arrays.

In [2]:
scalar = torch.tensor(7)
print(type(scalar))
print(f"Num of dimensions = {scalar.ndim}, since it is a scalar")
print(scalar.item())
print(f"Shape of scalar = {scalar.shape}")

<class 'torch.Tensor'>
Num of dimensions = 0, since it is a scalar
7
Shape of scalar = torch.Size([])


In [3]:
vector = torch.tensor([7,7])
print(f"Num of dimensions = {vector.ndim}")
print(f"Shape = {vector.shape}")

Num of dimensions = 1
Shape = torch.Size([2])


In [4]:
matrix = torch.tensor([[7,8],
                       [9,10]])
print("No of dimensions", matrix.ndim)
print("Shape of matrix",matrix.shape)

No of dimensions 2
Shape of matrix torch.Size([2, 2])


In [5]:
tensor = torch.tensor([[[1,2,],
                        [3,4],
                        [5,6]]])
print("No of dimensions",tensor.ndim)
print("SHape of tensor", tensor.shape)

No of dimensions 3
SHape of tensor torch.Size([1, 3, 2])


## Random tensor initialization
Used to create tensors randomly without explicitly specifying the input data

In [6]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.3741, 0.5772, 0.6829],
        [0.1043, 0.1262, 0.7440]])

In [7]:
random_img_tensor = torch.rand(size=(3,224,224))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [8]:
# create a tensor of all zeros
zeros = torch.zeros(2,3)
print(zeros)
print(zeros*random_tensor)
zeros.dtype

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.float32

In [9]:
# create a tensor of all ones
ones = torch.ones(2,3)
print(ones)
print(ones*random_tensor)
ones.dtype

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3741, 0.5772, 0.6829],
        [0.1043, 0.1262, 0.7440]])


torch.float32

## Range and tensor-like array creation

1. The end is not included. [start,end)
2. torch.*_like(source_tensor) retains the properties such as shape and ndim of the source_tensor.

In [10]:
one_ten = torch.arange(start=1, end=11, step=1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ten_zeros = torch.zeros_like(one_ten)
print(ten_zeros)
ten_ones = torch.ones_like(one_ten)
print(ten_ones)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


## Tensor Datatypes

1. The default datatype for floating point numbers is float32
2. The default datatype for whole numbers is int64
3. float32 is single-precision floating point where as float64 is called double precision floating point
4. Important params of tensor()
- dtype: datatype(float32, float64, int64, etc.,)
- device: type of device on which the tensor is loaded(cpu or gpu)
- requires_grad: tells whether gradients need to be computed or not

In [12]:
tensor_int64 = torch.tensor([1,2,3], dtype=None)
print(tensor_int64.dtype)
tensor_float32 = torch.tensor([1.0,2.0,3.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
print(tensor_float32.dtype)

torch.int64
torch.float32


In [13]:
tensor_float16_1 = torch.tensor([1.0,2.0,3.0],
                              dtype=torch.float16,
                              device=None)
tensor_float16_2 = tensor_float32.type(torch.float16)
tensor_float16_2

tensor([1., 2., 3.], dtype=torch.float16)

In [14]:
x = tensor_float32 * tensor_float16_1 # results in float32
x, x.dtype

(tensor([1., 4., 9.]), torch.float32)

- float64 : torch.float64/ torch.double
- int64 : torch.int64/ torch.long
- float16 : torch.float16/ torch.half

Tensor Attributes
1. tensor.shape
2. tensor.device
3. tensor.dtype

Tensor methods
- tensor.size()

In [15]:
tensor_eg = torch.tensor(
    data = [1,2,3],
    dtype=torch.half
)
print(tensor_eg.dtype, tensor_eg.device, tensor_eg.shape)
print(tensor_eg.size())

torch.float16 cpu torch.Size([3])
torch.Size([3])


## Tensor Operations


In [16]:
tensor = torch.tensor([1,2,3])
print("Addition",tensor+10)
print("Multiplication",tensor*10)
print("Exponent",tensor**3)

Addition tensor([11, 12, 13])
Multiplication tensor([10, 20, 30])
Exponent tensor([ 1,  8, 27])


In [17]:
# not inplace
torch.add(tensor,10)
torch.mul(tensor,0.1)

tensor([0.1000, 0.2000, 0.3000])

In [18]:
# in-place
tensor.add_(10)
tensor.mul_(2)

tensor([22, 24, 26])

## Multiplication
- Element-wise multiplication
- Matrix Multiplication

In [19]:
tensor = torch.tensor([1,2,3,])
print('Element-wise multiplication tensor*tensor is')
print(tensor*tensor)
new_tensor = torch.tensor([4,5,6])
print("new_tensor*tensor =",tensor*new_tensor)

Element-wise multiplication tensor*tensor is
tensor([1, 4, 9])
new_tensor*tensor = tensor([ 4, 10, 18])


In [20]:
# Matrix multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.29 ms, sys: 1.09 ms, total: 2.38 ms
Wall time: 9.82 ms


tensor(14)

In [21]:
%%time
value=0
for el in tensor:
    value+=el*el
print(value)

tensor(14)
CPU times: user 2.36 ms, sys: 45 µs, total: 2.4 ms
Wall time: 2.63 ms


In [22]:
mat_1 = torch.tensor([[1,2],
                      [3,4]])
mat_2 = torch.tensor([1,2])
print("torch.matmul(mat_1,mat_2) =",mat_1@mat_2)
print("torch.matmul(mat_2,mat_1) =",mat_2@mat_1)
print("torch.matmul automatically arranges the vector shapes")

torch.matmul(mat_1,mat_2) = tensor([ 5, 11])
torch.matmul(mat_2,mat_1) = tensor([ 7, 10])
torch.matmul automatically arranges the vector shapes


In [23]:
mat_1 = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])
mat_2 = torch.tensor([
    [7,8],
    [9,10],
    [11,12]
])
# torch.mm() is an alias to torch.mamtmul()/ @
try:
    print(torch.mm(mat_1,mat_2))
    print(mat_1.shape, mat_2.shape)
    print("Shape Error")
except:
    print(mat_1.shape, mat_2.T.shape)
    print(torch.mm(mat_1,mat_2.T))
    print("Transpose the mat_2 to make matmul valid")

torch.Size([3, 2]) torch.Size([2, 3])
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Transpose the mat_2 to make matmul valid


## Tensor Aggregation
min, max, mean and sum

In [24]:
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [25]:
x.min(), x.max()
# x.mean() -> fails because .mean() doesn't work on int64 dtype

(tensor(1), tensor(91))

In [26]:
x.type(torch.float32).mean()

tensor(46.)

In [27]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, Viewing and Stacking Tensors

- reshaping: reshapes into a defined shape
- view: returns a view of the input tensor but doesn't change it in the memory
- stacking: combine/concatenate multiple tensors
- squeeze: removes all `1` dimensions from a tensor
- unsqueeze: add a `1` dimension to a target tensor
- permute: return a view of the inpupt with dimensions swapped

In [28]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [29]:
# reshapes the tensor
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [30]:
# creates a view but does not modify the tensor in memory
z = x.view(1,9)
print(z,z.shape)
z[:,0] = 5
print(z,z.shape)
x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
# stacks the tensors and o/p tensor has a dimension more than the input tensor
x_stacked = torch.stack([x_reshaped,x_reshaped,x_reshaped], dim=0)
x_stacked, x_stacked.shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 torch.Size([3, 1, 9]))

In [32]:
# squeeze removes dim 1 in the input tensor
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape
print(f"Before squeezed: {x_reshaped, x_reshaped.shape}")
print(f"After squeezed dimension 1 is removed: {x_squeezed, x_squeezed.shape}")

Before squeezed: (tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))
After squeezed dimension 1 is removed: (tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))


In [33]:
# unsqueeze adds dim 1 in the specified dimension of the input tensor
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed, x_unsqueezed.shape)
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed, x_unsqueezed.shape)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])


In [36]:
# permute returns a view by swapping the dimensions in the specified order. modifying a value in view changes it in the original tensor since the view references the original
torch.manual_seed(seed=123)
y = torch.rand(size=(3,224,224))
print(y[0,0,0])
y[0,0,0] = 0.9
print(f"Original shape = {y.shape}")
y_perm1 = y.permute((0,1,2))
print(y_perm1[0,0,0])
print(f"Permuted 1 shape = {y_perm1.shape}")
y_perm2 = y.permute((1,0,2))
print(y_perm2[0,0,0])
print(f"Permuted 2 shape = {y_perm2.shape}")
y_perm3 = y.permute((1,2,0))
print(y_perm3[0,0,0])
print(f"Permuted 3 shape = {y_perm3.shape}")

tensor(0.2961)
Original shape = torch.Size([3, 224, 224])
tensor(0.9000)
Permuted 1 shape = torch.Size([3, 224, 224])
tensor(0.9000)
Permuted 2 shape = torch.Size([224, 3, 224])
tensor(0.9000)
Permuted 3 shape = torch.Size([224, 224, 3])


## Tensor Indexing

In [42]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [43]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
x[0,0]

tensor([1, 2, 3])

In [48]:
x[0,2,2]

tensor(9)

In [49]:
# we can use : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [56]:
x[:,:,1]

tensor([[2, 5, 8]])

In [59]:
x[:,1,1], x[0,1,1]

(tensor([5]), tensor(5))

In [60]:
# get index 0 of 0th dim and 1st dim and all values od 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [62]:
# index on x to return 9
print(x[0,2,2])

# index on x to return 3,6,9
x[0,:,2]

tensor(9)


tensor([3, 6, 9])

## PyTorch and NumPy

1. NumPy is a popular scientific python numerical computing library
2.  PyTorch has the functionality to interact with it

In [73]:
# numpy to tensor
import numpy as np
import torch
array = np.arange(1.0,8.0) # default dtype is float64 in numpy
# when an np array is converted to tensor, the tensor has dtype=float64 and this creates a new tensor in the memory that is changing tensor doesn't change the numpy array
tensor = torch.from_numpy(array)
array = array+1
print(array, tensor)

[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [74]:
# tensor to numpy
tensor = torch.ones(7)
tensor.dtype
np_tensor = tensor.numpy() # np_array has same dtype has tensor
print(tensor, np_tensor)
# changing tensor doesn't change the numpy array
tensor = tensor +1
print(tensor, np_tensor)


tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2.]) [1. 1. 1. 1. 1. 1. 1.]
