<a href="https://colab.research.google.com/github/srikrish2812/pytorch_practice/blob/main/torch_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Source: https://www.learnpytorch.io/00_pytorch_fundamentals/

## PyTorch Workflow

1. Get the data ready. Convert them to tensors
2. Build or pick a model including loss function, optimizer and build a training loop
3. Fit the model to the data and make a prediction
4. Evaluate the model/Hyperparameter tuning
5. Improve the model through experimentation

In [80]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)
!nvcc --version

2.5.1+cu121
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


## What is a Tensor?
1. It is a fundamental data structure in PyTorch used for storing and manipulating data.
2. Tensor computations can be parallelized on GPUs to improve the speed.
3. Tensors can be scalars, vectors or multi-dimensional arrays.

In [81]:
scalar = torch.tensor(7)
print(type(scalar))
print(f"Num of dimensions = {scalar.ndim}, since it is a scalar")
print(scalar.item())
print(f"Shape of scalar = {scalar.shape}")

<class 'torch.Tensor'>
Num of dimensions = 0, since it is a scalar
7
Shape of scalar = torch.Size([])


In [82]:
vector = torch.tensor([7,7])
print(f"Num of dimensions = {vector.ndim}")
print(f"Shape = {vector.shape}")

Num of dimensions = 1
Shape = torch.Size([2])


In [83]:
matrix = torch.tensor([[7,8],
                       [9,10]])
print("No of dimensions", matrix.ndim)
print("Shape of matrix",matrix.shape)

No of dimensions 2
Shape of matrix torch.Size([2, 2])


In [84]:
tensor = torch.tensor([[[1,2,],
                        [3,4],
                        [5,6]]])
print("No of dimensions",tensor.ndim)
print("SHape of tensor", tensor.shape)

No of dimensions 3
SHape of tensor torch.Size([1, 3, 2])


## Random tensor initialization
Used to create tensors randomly without explicitly specifying the input data

In [85]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.8549, 0.5509, 0.2868],
        [0.2063, 0.4451, 0.3593]])

In [86]:
random_img_tensor = torch.rand(size=(3,224,224))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [87]:
# create a tensor of all zeros
zeros = torch.zeros(2,3)
print(zeros)
print(zeros*random_tensor)
zeros.dtype

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.float32

In [88]:
# create a tensor of all ones
ones = torch.ones(2,3)
print(ones)
print(ones*random_tensor)
ones.dtype

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8549, 0.5509, 0.2868],
        [0.2063, 0.4451, 0.3593]])


torch.float32

## Range and tensor-like array creation

1. The end is not included. [start,end)
2. torch.*_like(source_tensor) retains the properties such as shape and ndim of the source_tensor.

In [89]:
one_ten = torch.arange(start=1, end=11, step=1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
ten_zeros = torch.zeros_like(one_ten)
print(ten_zeros)
ten_ones = torch.ones_like(one_ten)
print(ten_ones)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


## Tensor Datatypes

1. The default datatype for floating point numbers is float32
2. The default datatype for whole numbers is int64
3. float32 is single-precision floating point where as float64 is called double precision floating point
4. Important params of tensor()
- dtype: datatype(float32, float64, int64, etc.,)
- device: type of device on which the tensor is loaded(cpu or gpu)
- requires_grad: tells whether gradients need to be computed or not

In [91]:
tensor_int64 = torch.tensor([1,2,3], dtype=None)
print(tensor_int64.dtype)
tensor_float32 = torch.tensor([1.0,2.0,3.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
print(tensor_float32.dtype)

torch.int64
torch.float32


In [92]:
tensor_float16_1 = torch.tensor([1.0,2.0,3.0],
                              dtype=torch.float16,
                              device=None)
tensor_float16_2 = tensor_float32.type(torch.float16)
tensor_float16_2

tensor([1., 2., 3.], dtype=torch.float16)

In [93]:
x = tensor_float32 * tensor_float16_1 # results in float32
x, x.dtype

(tensor([1., 4., 9.]), torch.float32)

- float64 : torch.float64/ torch.double
- int64 : torch.int64/ torch.long
- float16 : torch.float16/ torch.half

Tensor Attributes
1. tensor.shape
2. tensor.device
3. tensor.dtype

Tensor methods
- tensor.size()

In [94]:
tensor_eg = torch.tensor(
    data = [1,2,3],
    dtype=torch.half
)
print(tensor_eg.dtype, tensor_eg.device, tensor_eg.shape)
print(tensor_eg.size())

torch.float16 cpu torch.Size([3])
torch.Size([3])


## Tensor Operations


In [95]:
tensor = torch.tensor([1,2,3])
print("Addition",tensor+10)
print("Multiplication",tensor*10)
print("Exponent",tensor**3)

Addition tensor([11, 12, 13])
Multiplication tensor([10, 20, 30])
Exponent tensor([ 1,  8, 27])


In [96]:
# not inplace
torch.add(tensor,10)
torch.mul(tensor,0.1)

tensor([0.1000, 0.2000, 0.3000])

In [97]:
# in-place
tensor.add_(10)
tensor.mul_(2)

tensor([22, 24, 26])

## Multiplication
- Element-wise multiplication
- Matrix Multiplication

In [98]:
tensor = torch.tensor([1,2,3,])
print('Element-wise multiplication tensor*tensor is')
print(tensor*tensor)
new_tensor = torch.tensor([4,5,6])
print("new_tensor*tensor =",tensor*new_tensor)

Element-wise multiplication tensor*tensor is
tensor([1, 4, 9])
new_tensor*tensor = tensor([ 4, 10, 18])


In [99]:
# Matrix multiplication
%%time
torch.matmul(tensor,tensor)

CPU times: user 32 µs, sys: 6 µs, total: 38 µs
Wall time: 43.6 µs


tensor(14)

In [100]:
%%time
value=0
for el in tensor:
    value+=el*el
print(value)

tensor(14)
CPU times: user 313 µs, sys: 0 ns, total: 313 µs
Wall time: 318 µs


In [101]:
mat_1 = torch.tensor([[1,2],
                      [3,4]])
mat_2 = torch.tensor([1,2])
print("torch.matmul(mat_1,mat_2) =",mat_1@mat_2)
print("torch.matmul(mat_2,mat_1) =",mat_2@mat_1)
print("torch.matmul automatically arranges the vector shapes")

torch.matmul(mat_1,mat_2) = tensor([ 5, 11])
torch.matmul(mat_2,mat_1) = tensor([ 7, 10])
torch.matmul automatically arranges the vector shapes


In [102]:
mat_1 = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])
mat_2 = torch.tensor([
    [7,8],
    [9,10],
    [11,12]
])
# torch.mm() is an alias to torch.mamtmul()/ @
try:
    print(torch.mm(mat_1,mat_2))
    print(mat_1.shape, mat_2.shape)
    print("Shape Error")
except:
    print(mat_1.shape, mat_2.T.shape)
    print(torch.mm(mat_1,mat_2.T))
    print("Transpose the mat_2 to make matmul valid")

torch.Size([3, 2]) torch.Size([2, 3])
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Transpose the mat_2 to make matmul valid


## Tensor Aggregation
min, max, mean and sum

In [103]:
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [104]:
x.min(), x.max()
# x.mean() -> fails because .mean() doesn't work on int64 dtype

(tensor(1), tensor(91))

In [105]:
x.type(torch.float32).mean()

tensor(46.)

In [106]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, Viewing and Stacking Tensors

- reshaping: reshapes into a defined shape
- view: returns a view of the input tensor but doesn't change it in the memory
- stacking: combine/concatenate multiple tensors
- squeeze: removes all `1` dimensions from a tensor
- unsqueeze: add a `1` dimension to a target tensor
- permute: return a view of the inpupt with dimensions swapped

In [107]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [108]:
# reshapes the tensor
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [109]:
# creates a view but does not modify the tensor in memory
z = x.view(1,9)
print(z,z.shape)
z[:,0] = 5
print(z,z.shape)
x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [110]:
# stacks the tensors and o/p tensor has a dimension more than the input tensor
x_stacked = torch.stack([x_reshaped,x_reshaped,x_reshaped], dim=0)
x_stacked, x_stacked.shape

(tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[5., 2., 3., 4., 5., 6., 7., 8., 9.]],
 
         [[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]),
 torch.Size([3, 1, 9]))

In [111]:
# squeeze removes dim 1 in the input tensor
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape
print(f"Before squeezed: {x_reshaped, x_reshaped.shape}")
print(f"After squeezed dimension 1 is removed: {x_squeezed, x_squeezed.shape}")

Before squeezed: (tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))
After squeezed dimension 1 is removed: (tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))


In [112]:
# unsqueeze adds dim 1 in the specified dimension of the input tensor
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed, x_unsqueezed.shape)
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed, x_unsqueezed.shape)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])


In [113]:
# permute returns a view by swapping the dimensions in the specified order. modifying a value in view changes it in the original tensor since the view references the original
torch.manual_seed(seed=123)
y = torch.rand(size=(3,224,224))
print(y[0,0,0])
y[0,0,0] = 0.9
print(f"Original shape = {y.shape}")
y_perm1 = y.permute((0,1,2))
print(y_perm1[0,0,0])
print(f"Permuted 1 shape = {y_perm1.shape}")
y_perm2 = y.permute((1,0,2))
print(y_perm2[0,0,0])
print(f"Permuted 2 shape = {y_perm2.shape}")
y_perm3 = y.permute((1,2,0))
print(y_perm3[0,0,0])
print(f"Permuted 3 shape = {y_perm3.shape}")

tensor(0.2961)
Original shape = torch.Size([3, 224, 224])
tensor(0.9000)
Permuted 1 shape = torch.Size([3, 224, 224])
tensor(0.9000)
Permuted 2 shape = torch.Size([224, 3, 224])
tensor(0.9000)
Permuted 3 shape = torch.Size([224, 224, 3])


## Tensor Indexing

In [114]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [115]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [116]:
x[0,0]

tensor([1, 2, 3])

In [117]:
x[0,2,2]

tensor(9)

In [118]:
# we can use : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [119]:
x[:,:,1]

tensor([[2, 5, 8]])

In [120]:
x[:,1,1], x[0,1,1]

(tensor([5]), tensor(5))

In [121]:
# get index 0 of 0th dim and 1st dim and all values od 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [122]:
# index on x to return 9
print(x[0,2,2])

# index on x to return 3,6,9
x[0,:,2]

tensor(9)


tensor([3, 6, 9])

## PyTorch and NumPy

1. NumPy is a popular scientific python numerical computing library
2.  PyTorch has the functionality to interact with it

In [123]:
# numpy to tensor
import numpy as np
import torch
array = np.arange(1.0,8.0) # default dtype is float64 in numpy
# when an np array is converted to tensor, the tensor has dtype=float64 and this creates a new tensor in the memory that is changing tensor doesn't change the numpy array
tensor = torch.from_numpy(array)
array = array+1
print(array, tensor)

[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [124]:
# tensor to numpy
tensor = torch.ones(7)
tensor.dtype
np_tensor = tensor.numpy() # np_array has same dtype has tensor
print(tensor, np_tensor)
# changing tensor doesn't change the numpy array
tensor = tensor +1
print(tensor, np_tensor)


tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2.]) [1. 1. 1. 1. 1. 1. 1.]


## Reproducibility in Tensors

- torch.manual_seed(seed) removes the randomness in the random initializes of tensors and makes then reproducuble

In [125]:
torch.manual_seed(seed=1234567890)
A = torch.rand(3,3)
B = torch.rand(3,3)
print(A,B, A==B)

torch.manual_seed(seed=1234567890)
A = torch.rand(3,3)
torch.manual_seed(seed=1234567890)
B = torch.rand(3,3)
print(A,B,A==B)

tensor([[0.4115, 0.1703, 0.4556],
        [0.1519, 0.5030, 0.5041],
        [0.2636, 0.5436, 0.1373]]) tensor([[0.2508, 0.2161, 0.4232],
        [0.3683, 0.7578, 0.0032],
        [0.3863, 0.2643, 0.1759]]) tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[0.4115, 0.1703, 0.4556],
        [0.1519, 0.5030, 0.5041],
        [0.2636, 0.5436, 0.1373]]) tensor([[0.4115, 0.1703, 0.4556],
        [0.1519, 0.5030, 0.5041],
        [0.2636, 0.5436, 0.1373]]) tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## Running on GPUs

CUDA + NVIDIA + PyTorch == insane_computation speeds

In [126]:
!nvidia-smi

Mon Jan 20 03:08:58 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P0              29W /  70W |    151MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [127]:
torch.cuda.is_available()

True

In [128]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device =", device)
print("Number of GPUs =", torch.cuda.device_count())

Device = cuda
Number of GPUs = 1


## Setup device agnostic code and putting tensor on and off GPU

In [129]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [130]:
# move tensor to gpu if available
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device =", device)
print("Number of GPUs =", torch.cuda.device_count())
tensor_gpu = tensor.to(device)
print(tensor_gpu)

Device = cuda
Number of GPUs = 1
tensor([1, 2, 3], device='cuda:0')


In [131]:
# move tensors back to cpu
tensor_cpu = tensor_gpu.cpu()
print(tensor_cpu, tensor_gpu)

tensor([1, 2, 3]) tensor([1, 2, 3], device='cuda:0')


## Exercises and Problems

In [132]:
# 2. Create a random tensor with shape (7, 7).
tensor_1 = torch.rand(7,7)
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
tensor_2 = torch.rand(1,7)
tensor_3 = tensor_1@tensor_2.T
tensor_3

tensor([[1.3164],
        [2.0284],
        [1.9704],
        [1.5392],
        [1.7770],
        [2.0452],
        [1.4453]])

In [133]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(0)
tensor_1 = torch.rand(7,7)
tensor_2 = torch.rand(1,7)
tensor_3 = tensor_1@tensor_2.T
tensor_3

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [134]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(seed=1234)

In [135]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)
torch.manual_seed(1234)
tensor_1 = torch.rand(2,3).cuda()
tensor_2 = torch.rand(2,3).cuda()
tensor_1, tensor_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [136]:
# 7.Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
tensor_3 = tensor_1@tensor_2.T
tensor_3

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [137]:
# 8. Find the maximum and minimum values of the output of 7.
max_tensor_3 = tensor_3.max()
min_tensor_3 = tensor_3.min()
print(f"Maximum value in tensor_3 = {max_tensor_3}")
print(f"Minimum value in tensor_3 = {min_tensor_3}")

Maximum value in tensor_3 = 0.5617256760597229
Minimum value in tensor_3 = 0.3647301495075226


In [138]:
# 9. Find the maximum and minimum index values of the output of 7.
maxindex_tensor_3 = tensor_3.argmax()
minindex_tensor_3 = tensor_3.argmin()
print(f"Maximum index value in tensor_3 = {maxindex_tensor_3}")
print(f"Minimum index value in tensor_3 = {minindex_tensor_3}")

Maximum index value in tensor_3 = 3
Minimum index value in tensor_3 = 0


In [139]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(seed=7)
x = torch.rand(1,1,1,10)
y = x.squeeze()
print(f"x, shape of x = {x}, {x.shape}")
print(f"x, shape of y = {y}, {y.shape}")

x, shape of x = tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10])
x, shape of y = tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10])
