## PyTorch Fundamentals

Source: https://www.learnpytorch.io/00_pytorch_fundamentals/

## PyTorch Workflow

1. Get the data ready. Convert them to tensors
2. Build or pick a model including loss function, optimizer and build a training loop
3. Fit the model to the data and make a prediction
4. Evaluate the model/Hyperparameter tuning
5. Improve the model through experimentation

In [1]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)
!nvcc --version

2.5.1+cu121
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


## What is a Tensor?
1. It is a fundamental data structure in PyTorch used for storing and manipulating data.
2. Tensor computations can be parallelized on GPUs to improve the speed.
3. Tensors can be scalars, vectors or multi-dimensional arrays.

In [2]:
scalar = torch.tensor(7)
print(type(scalar))
print(f"Num of dimensions = {scalar.ndim}, since it is a scalar")
print(scalar.item())
print(f"Shape of scalar = {scalar.shape}")

<class 'torch.Tensor'>
Num of dimensions = 0, since it is a scalar
7
Shape of scalar = torch.Size([])


In [3]:
vector = torch.tensor([7,7])
print(f"Num of dimensions = {vector.ndim}")
print(f"Shape = {vector.shape}")

Num of dimensions = 1
Shape = torch.Size([2])


In [4]:
matrix = torch.tensor([[7,8],
                       [9,10]])
print("No of dimensions", matrix.ndim)
print("Shape of matrix",matrix.shape)

No of dimensions 2
Shape of matrix torch.Size([2, 2])


In [5]:
tensor = torch.tensor([[[1,2,],
                        [3,4],
                        [5,6]]])
print("No of dimensions",tensor.ndim)
print("SHape of tensor", tensor.shape)

No of dimensions 3
SHape of tensor torch.Size([1, 3, 2])


## Random tensor initialization
Used to create tensors randomly without explicitly specifying the input data

In [6]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.6272, 0.4020, 0.5970],
        [0.9042, 0.4120, 0.9871]])

In [7]:
random_img_tensor = torch.rand(size=(3,224,224))
random_img_tensor.shape, random_img_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [8]:
# create a tensor of all zeros
zeros = torch.zeros(2,3)
print(zeros)
print(zeros*random_tensor)
zeros.dtype

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.float32

In [9]:
# create a tensor of all ones
ones = torch.ones(2,3)
print(ones)
print(ones*random_tensor)
ones.dtype

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6272, 0.4020, 0.5970],
        [0.9042, 0.4120, 0.9871]])


torch.float32

## Range and tensor-like array creation

1. The end is not included. [start,end)
2. torch.*_like(source_tensor) retains the properties such as shape and ndim of the source_tensor.

In [10]:
one_ten = torch.arange(start=1, end=11, step=1)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
ten_zeros = torch.zeros_like(one_ten)
print(ten_zeros)
ten_ones = torch.ones_like(one_ten)
print(ten_ones)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


## Tensor Datatypes

1. The default datatype for floating point numbers is float32
2. The default datatype for whole numbers is int64
3. float32 is single-precision floating point where as float64 is called double precision floating point
4. Important params of tensor()
- dtype: datatype(float32, float64, int64, etc.,)
- device: type of device on which the tensor is loaded(cpu or gpu)
- requires_grad: tells whether gradients need to be computed or not

In [12]:
tensor_int64 = torch.tensor([1,2,3], dtype=None)
print(tensor_int64.dtype)
tensor_float32 = torch.tensor([1.0,2.0,3.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
print(tensor_float32.dtype)

torch.int64
torch.float32


In [15]:
tensor_float16_1 = torch.tensor([1.0,2.0,3.0],
                              dtype=torch.float16,
                              device=None)
tensor_float16_2 = tensor_float32.type(torch.float16)
tensor_float16_2

tensor([1., 2., 3.], dtype=torch.float16)

In [18]:
x = tensor_float32 * tensor_float16_1
x, x.dtype

(tensor([1., 4., 9.]), torch.float32)

## Tensor attributes